# ãƒ‡ã‚£ãƒ¬ã‚¯ãƒˆãƒªã‚’è¡¨ç¤º

[directory]
truncation_length = 10
truncate_to_repo = false

# ãƒ†ã‚­ã‚¹ãƒˆãŒå…¥åŠ›ã•ã‚Œã‚‹å ´æ‰€ã®æ¨ªã«æ–‡å­—

[character]
success_symbol = "ğŸ¦„"
error_symbol = "â˜”ï¸"

# ãƒ¢ã‚¸ãƒ¥ãƒ¼ãƒ«ã‚’ç„¡åŠ¹åŒ–

[nodejs]
disabled = true

[package]
disabled = true

[php]
disabled = true